version: '3.7'
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
      MYSQL_DATABASE: thrive
      MYSQL_USER: root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --default-storage-engine=INNODB
      --transaction-isolation=READ-COMMITTED
      --sql_mode=NO_AUTO_VALUE_ON_ZERO
      --binlog_format=row
      --log_bin_trust_function_creators=1
    ports:
      - "13000:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  blog:
    image: registry.cn-chengdu.aliyuncs.com/lyx_blog/thrive-blog
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/thrive?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - web

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/nginx/ssl
    restart: always
    depends_on:
      - blog
    networks:
      - web

networks:
  web:
    name: web
    driver: bridge